version: '3'
services:
  app:
    container_name : auditlog-microservice
    build: .
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - APP_NAME=auditlog-microservice
    volumes:
      - ./Web:/app
    networks:
      - auditlog_network
  mongo:
    container_name: mongodb
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=N62s32N41
    ports:
      - 27019:27017
    restart: always
    volumes:
      - ./Docker/mongodb_data:/data/db
    networks:
      - auditlog_network
networks:
  auditlog_network:
    external:
      name: auditlog_network
